export const GAME_PHASES = {
  MODE_SELECTION: 'MODE_SELECTION',
  ONLINE_SETUP: 'ONLINE_SETUP',
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_LOBBY: 'ROOM_LOBBY',
  CLUE_PHASE: 'CLUE_PHASE',
  VOTE_PHASE: 'VOTE_PHASE',
}

export const PLAYER_STATUS = { JOINED: 'JOINED', READY: 'READY', SPECTATOR: 'SPECTATOR', DISCONNECTED: 'DISCONNECTED' }
